version: '3'
services:

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    #    volumes:
    #      - ./mydir:/mydir # 文件挂载
    #      - ./datadir:/var/lib/mysql # 挂载目录
    #      - ./conf/my.cnf:/etc/mysql/my.cnf # 挂载 my.cnf 配置文件
    #      - ./docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=pFtaF1QF"  # 设置密码
      - "TZ=Asia/Shanghai"
    ports:
      - 6306:3306

  redis_no_persistent:
    container_name: "redis_no_persistent"
    image: redis:7.2.5
    restart: always
    command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "google@google.com"
      ZO_ROOT_USER_PASSWORD: "L12sXy8d"
    ports:
      - "5080:5080"
    volumes:
      - data:/data

volumes:
  data: